import { Inter } from "next/font/google";
import "./globals.css";
import  { NavbarAnon, Navbara } from "@/components/Navbara";
import Footers from "@/components/Footer";
import { getSessionUser } from "@/lib/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "tiny url",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getSessionUser()
  const loggedIn = user !== null
   
  const Navbar = loggedIn ? <Navbara/> : <NavbarAnon/>;
  return (
    <html lang="en">      
      <body className={inter.className}>
        
        {Navbar}
        {children}
        <Footers />
        </body>
    </html>
  );
}
