import { Inter } from "next/font/google";
import "./globals.css";
import Navbara from "@/components/Navbara";
import Footers from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "tiny url",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">      
      <body className={inter.className}>
        
        <Navbara />
        {children}
        <Footers />
        </body>
    </html>
  );
}
